name: Build and deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./app

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'yarn'
        cache-dependency-path: app/yarn.lock

    - name: Install dependencies
      run: yarn install

    - name: Run tests
      continue-on-error: true
      run: yarn redwood test web --no-watch --silent --ci

    - name: Build web
      env:
        INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
        NFTPORT_API_KEY: ${{ secrets.NFTPORT_API_KEY }}
      run: yarn redwood build web

    - name: Deploy to Skynet
      uses: SkynetLabs/deploy-to-skynet-action@v2
      with:
        upload-dir: app/web/dist
        github-token: ${{ secrets.GITHUB_TOKEN }}
